org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.11.10

minecraft_version=1.21.1
neo_version=21.1.248
tfc_version=4.2.9
patchouli_version=1.21.1-92-NEOFORGE
tfc_toroidal_compat_version=0.1.0
toroidal_world_version=XTSSZLoy
tfc_mantle_mountains_version=9ysJZxSq
journeymap_version=3xPNjfk3
