modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="tfc_toroidal_compat"
version="${mod_version}"
displayName="TFC Toroidal Compatibility"
authors="DigitsCodeCompendium"
description='''
Makes TerraFirmaCraft's custom terrain noise continuous across Toroidal World seams.
'''

[[dependencies.tfc_toroidal_compat]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.tfc_toroidal_compat]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.tfc_toroidal_compat]]
modId="tfc"
type="required"
versionRange="[${tfc_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.tfc_toroidal_compat]]
modId="toroidal_world"
type="required"
versionRange="[0.14.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.tfc_toroidal_compat]]
modId="tfcmountains"
type="optional"
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="tfc_toroidal_compat.mixins.json"
