modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="DigitsCodeCompendium"
description='''
Makes TerraFirmaCraft's custom terrain noise continuous across Toroidal World seams.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tfc"
type="required"
versionRange="[${tfc_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="toroidal_world"
type="required"
versionRange="[0.14.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tfcmountains"
type="optional"
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="journeymap"
type="optional"
versionRange="[1.21.1-6.0.0,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="tfc_toroidal_compat.mixins.json"
